### ISSUE TITLE
Integração com bagisto

### ISSUE THREAD

**Issue by marcelowu** [somosgad/laravel-payu#1]
A Free and Opensource laravel eCommerce framework built for all to build and scale your business. [https://bagisto.com](url)
possivel integra com bagisto, pretende fazer um plugins para bagisto

**Comment by giovannipds** [comment]
**EN:** Hi @marcelowu, what's up? We're currently still developing this package for our own use case, so many features aren't available yet.

At the beginning, we're not looking forward or investing our effort to support Bagisto now, though I believe it it would be a nice integration to the package!

Feel free to contribute with us to make this package support Bagisto, we would happily help you in what we're able.

Hugs, Gio.

---

**PT-BR:** Oi Marcelo, tudo bem? Nós ainda estamos desenvolvendo esse pacote para nosso uso em específico, então muitas funcionalidades ainda não estão dispnóveis.

Num primeiro momento nós não estamos planejando investir nossos eforços em suportar o Bagisto agora, embora eu realmente acredite que seja uma integração bem legal para o pacote!

Sinta-se livre para contribuir com a gente para fazer esse pacote suportar o Bagisto, faremos o possível para te ajudar no que precisar.

Abraços!

**Comment by marcelowu** [comment]
obrigado
